# Raw candidate pool of Zurich-area Treuhänder, sourced via web search.
# (name, homepage_url). Aggregators/portals/national giants excluded.
CANDIDATES = [
    ("Zuritreuhand", "https://zuritreuhand.ch/"),
    ("MRG Treuhand", "https://www.mrg-treuhand.ch/"),
    ("ZH Treuhand", "https://zhtreuhand.ch/"),
    ("KMU Treuhandexperte GmbH", "https://www.kmu-trex.ch/"),
    ("STM Treuhand Mettler AG", "https://stmtreuhand.ch/"),
    ("Maurer Treuhand", "https://www.maurer-treuhand.ch/"),
    ("kmuTREUHAND", "https://www.kmutreuhand.com/"),
    ("Zurich Tax & Treuhand GmbH", "https://zurichtaxtreuhand.ch/"),
    ("Treuhandbüro Graf AG", "https://www.treuhandgraf.ch/"),
    ("Treuhandzentrum Zürich AG", "https://www.treuhand-zentrum-zuerich.ch/"),
    ("Swiss Treuhand Siegrist GmbH", "https://www.treuhandsiegrist.ch/"),
    ("Treuhandfinanz / Treuhänder Zürich", "https://www.treuhaender-zuerich.com/"),
    ("KBT / Smart Treuhand AG", "https://www.kbt.ch/"),
    ("Treuhand Zürich (treuhand-zuerich.com)", "https://www.treuhand-zuerich.com/"),
    ("Divisia Treuhand AG", "https://divisia-treuhand.ch/"),
    ("Accuratus Treuhand", "https://accuratus-treuhand.ch/"),
    ("Fuchs Treuhand AG", "https://www.fuchstreuhand.ch/"),
    ("Interconsulta", "https://www.interconsulta.ch/"),
    ("Würth Treuhand AG", "https://www.wuerth-treuhand.ch/"),
    ("Swiss Revision AG", "https://www.swiss-revision.ch/"),
    ("STG Zürich", "https://www.stg.zuerich/"),
    ("SEBONA Treuhand", "https://www.sebona-treuhand.ch/"),
    ("V-Buchhaltung", "https://www.v-buchhaltung.ch/"),
    ("Müller & Schuhmacher AG", "https://www.mueller-schuhmacher.ch/"),
    ("Hermann Treuhand", "https://hermanntreuhand.ch/"),
    ("Treuhand mit Herz", "https://www.treuhandmitherz.ch/"),
    ("One Treuhand", "https://www.onetreuhand.ch/"),
    ("Monere Wallisellen", "https://www.monere.ch/"),
    ("Global-Treuhand GmbH", "https://www.global-treuhand.ch/"),
    ("Rebex AG", "https://www.rebex.ch/"),
    ("Treuhandbüro Balbiani", "https://www.balbiani.ch/"),
    ("Langhart & Partner Treuhand AG", "https://langhart-partner.ch/"),
    ("Büchi Treuhand und Verwaltung", "https://buechi-treuhand.ch/"),
    ("aawi treuhand ag", "https://www.aawi.ch/"),
    ("SBT Treuhand Zürich", "https://www.sbt-treuhand.ch/"),
    ("SPP Treuhand AG", "https://spp-treuhand.ch/"),
    ("Treuhandbüro Ivanova / Adea", "https://adea-treuhand.ch/"),
    ("Treuhand Catherine Schmid GmbH", "https://www.treuhandschmid.ch/"),
    ("SteuerVogt GmbH", "https://steuervogt.ch/"),
    ("MK Treuhand", "https://mkfiduciaire.ch/"),
    ("aurora treuhand ag", "https://www.aurora-treuhand.ch/"),
    ("Steuerberater365 Zürich", "https://www.steuerberater365-zuerich.ch/"),
    ("Turicum Treuhand AG", "https://www.turicum-treuhand.ch/"),
    ("L+A Treuhand", "https://www.latreuhand.ch/"),
    ("Fierz Steuerberatung GmbH", "https://www.fierz-steuern.ch/"),
    ("Treuhand Service Zürich", "https://www.treuhand-service-zh.ch/"),
    ("Urania Treuhand AG", "https://www.urania-treuhand.ch/"),
    ("Wespi & Partner AG", "https://wespipartner.ch/"),
    ("Schnell Treuhand AG", "https://www.schnelltreuhand.ch/"),
    ("Dr. Iten, Dudli + Partner", "https://idp-treuhand.ch/"),
    ("Steuri + Partner AG", "https://steuritreuhand.ch/"),
    ("Budliger Treuhand AG", "https://budliger.ch/"),
    ("Suter Treuhand", "https://sutertreuhand.ch/"),
    ("HMR Partner Treuhand AG", "https://hmrpartner.ch/"),
    ("Schweizerische Treuhandgesellschaft Revision AG", "https://www.stg-revision.ch/"),
    ("Taxalis Treuhand AG", "https://www.taxalis.ch/"),
    ("Lanz & Partner Treuhand AG", "https://www.lanz-partner.ch/"),
    ("Treuhandbüro24 Zürich", "https://www.treuhandbuero24.ch/"),
    ("Steuerberatung Schweiz", "https://www.steuerberatung-schweiz.ch/"),
    ("ACCURATA Holding / Turicum", "https://www.accurata.ch/"),
]
